# syntax=docker/dockerfile:1

# the importance of optimized builds
# REPOSITORY   TAG       IMAGE ID       CREATED              SIZE
# app_prod     latest    4053cdad9d2a   9 seconds ago        65.5MB
# app_dev      latest    29bc1dcbd8e8   About a minute ago   1.08GB

ARG \
    PYTHON_VERSION=3.9

FROM python:${PYTHON_VERSION}

ENV \
    # python
    PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    # if we are developing live
    # PYTHONDONTWRITEBYTECODE=1 \
    # poetry
    POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_CREATE=false \
    POETRY_CACHE_DIR='/var/cache/pypoetry' \
    POETRY_HOME='/usr/local' \
    # flask
    FLASK_ENV=development \
    FLASK_DEBUG=True

WORKDIR /app

# layers: dependency installation
COPY ./poetry.lock ./pyproject.toml ./
RUN set -ex \
    && pip install poetry \
    && poetry install --no-root --no-ansi --no-interaction

# layer: copy app
COPY app.py ./
ENTRYPOINT [ "flask" ]
CMD [ "run", "--host", "0.0.0.0", "--port", "5000" ]
