apiVersion: v1
kind: Service
metadata:
  name: flask-app-deployment
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
